services:
  game:
    build:
      context: .
    network_mode: "host"
    stdin_open: true
    tty: true
    # O comando será passado via linha de comando ou variáveis de ambiente
    # Exemplo de uso local: docker compose run game --name Player --port 50051
