syntax = "proto3";

message Empty {}

service PeerDiscovery {
    rpc RegisterPeer (Peer) returns (Empty);
    rpc GetPeers (Empty) returns (AllPeers);
    rpc RemovePeer (Peer) returns (Empty);
}

message Peer {
  string uuid = 1;
  string address = 2;
  string username = 3;
}

message AllPeers {
    map<string, PeerInfo> peers = 1;
}

message PeerInfo {
  string address = 1;
  string username = 2;
}

service Chat {
  rpc Broadcast (BroadcastMessage) returns (Empty);
  rpc Unicast (UnicastMessage) returns (Empty);
}

message BroadcastMessage {
  string from_uuid = 1;
  string text = 2;
}

message UnicastMessage {
  string from_uuid = 1;
  string text = 2;
}
