# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import game_pb2 as proto_dot_game__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/game_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameServiceStub(object):
    """─────────────────────────────────────────────
    Player actions sent between peers
    ─────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendAction = channel.unary_unary(
                '/game.GameService/SendAction',
                request_serializer=proto_dot_game__pb2.ActionRequest.SerializeToString,
                response_deserializer=proto_dot_game__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.FindNode = channel.unary_unary(
                '/game.GameService/FindNode',
                request_serializer=proto_dot_game__pb2.FindNodeRequest.SerializeToString,
                response_deserializer=proto_dot_game__pb2.FindNodeResponse.FromString,
                _registered_method=True)
        self.StoreNode = channel.unary_unary(
                '/game.GameService/StoreNode',
                request_serializer=proto_dot_game__pb2.StoreNodeRequest.SerializeToString,
                response_deserializer=proto_dot_game__pb2.StoreNodeResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/game.GameService/Ping',
                request_serializer=proto_dot_game__pb2.PingRequest.SerializeToString,
                response_deserializer=proto_dot_game__pb2.PingResponse.FromString,
                _registered_method=True)


class GameServiceServicer(object):
    """─────────────────────────────────────────────
    Player actions sent between peers
    ─────────────────────────────────────────────
    """

    def SendAction(self, request, context):
        """Combat / interaction actions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindNode(self, request, context):
        """DHT-based peer discovery
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAction,
                    request_deserializer=proto_dot_game__pb2.ActionRequest.FromString,
                    response_serializer=proto_dot_game__pb2.ActionResponse.SerializeToString,
            ),
            'FindNode': grpc.unary_unary_rpc_method_handler(
                    servicer.FindNode,
                    request_deserializer=proto_dot_game__pb2.FindNodeRequest.FromString,
                    response_serializer=proto_dot_game__pb2.FindNodeResponse.SerializeToString,
            ),
            'StoreNode': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreNode,
                    request_deserializer=proto_dot_game__pb2.StoreNodeRequest.FromString,
                    response_serializer=proto_dot_game__pb2.StoreNodeResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=proto_dot_game__pb2.PingRequest.FromString,
                    response_serializer=proto_dot_game__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'game.GameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('game.GameService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameService(object):
    """─────────────────────────────────────────────
    Player actions sent between peers
    ─────────────────────────────────────────────
    """

    @staticmethod
    def SendAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game.GameService/SendAction',
            proto_dot_game__pb2.ActionRequest.SerializeToString,
            proto_dot_game__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game.GameService/FindNode',
            proto_dot_game__pb2.FindNodeRequest.SerializeToString,
            proto_dot_game__pb2.FindNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game.GameService/StoreNode',
            proto_dot_game__pb2.StoreNodeRequest.SerializeToString,
            proto_dot_game__pb2.StoreNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game.GameService/Ping',
            proto_dot_game__pb2.PingRequest.SerializeToString,
            proto_dot_game__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
